import './globals.css';
import { Inter } from 'next/font/google';
import noise from "../assets/images/Noise.png";

const inter = Inter({ subsets: ['latin'] })

const bodyStyle = {
  backgroundImage: `url(${noise.src})`,
  height: "100%"
}

export const metadata = {
  title: 'Abdukarim Mirzayev',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./favicon.ico"/>
      </head>
      <body style={bodyStyle} className={inter.className}>{children}</body>
    </html>
  )
}
